name: Publish Docker image [master]

on: 
  workflow_dispatch:
    branches: [ master]
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # prepara l'enviroment con Java versione 16
      - name: Set up JDK 16
        uses: actions/setup-java@v2 
        with: # condizioni
          java-version: '16'
          distribution: 'adopt'
          cache: maven
        # non uso l'action: docker/build-push-action@v2, perche'
        # jhipster costruisce l'immagine docker con jdb e non piu'
        # utilizzando il Dockerfile.
      - name: Build and push
        run: mvnw package -Pprod verify jib:build

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}