name: Publish Docker image [master]

on: 
  workflow_dispatch:
    branches: [ master]
    
jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:  
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # non uso l'action: docker/build-push-action@v2, perche'
        # jhipster costruisce l'immagine docker con jdb e non piu'
        # utilizzando il Dockerfile.
      - name: Build and push
        run: mvn compile jib:build