# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD with Maven [master]

# push e' l'evento che triggera il workflow
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
    
jobs:

  # deploy su Amazon Elastic Beanstalk  
  elastic-beanstalk-deployment:
    runs-on: ubuntu-latest
    #needs: maven-integration-test
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: prod verify
        run: mvn -Pprod verify
      - name: Generate deployment package
        run: zip -r v0.0.2-SNAP.zip Procfile warehouse-0.0.2-SNAPSHOT.jar
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: warehouse1
          environment_name: Warehouse1-env
          version_label: 0.0.2-SNAPSHOT
          region: eu-west-1
          deployment_package: 0.0.2-SNAP.zip
